/* @author Praveen Reddy 
 * @date : 2021-10-13
 * @desc Thread ids
 */

#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <unistd.h>
#include <pthread.h>
#include <sys/syscall.h>
#include <fcntl.h>
#include <sys/types.h>

void thread_handler(void* args){ //function to be executed when a thread is created 

    //printf("Thread Running...%lu\n",syscall(__NR_gettid));
    printf("Thread Running...%lu\n",pthread_self());
    sleep(1);
}

int main(){

    pthread_t thread;

    for(int i=0;i<3;i++){
        int retval=pthread_create(&thread,NULL,(void*)thread_handler, NULL);

        if(retval==-1){
            perror("pthread_create");
            exit(EXIT_FAILURE);
        }
        //pthread_join(thread,NULL);
    }
    pthread_exit(NULL);
    
    return 0;
}
/*The ID generated by pthread_self() is reused by the threading implementation after the thread completion and the ID assigned by the kernel is unique one...
 *So the difference between gettid() and the pthread_self() is:
 *1.)POSIX thread IDs are assigned and maintained by the threading implementation. The thread ID returned by gettid() is a number (similar to a process ID) that is assigned by the kernel.
 *2.)ID generated by the pthread_self() can be used after the completion of the thread but  the ID genereated by the kernel can't be used even after the completion of the thread..
*/

/*POSIX thread IDs are not the same as the thread IDs returned by the Linux specific gettid() system call. 
 *POSIX thread IDs are assigned and maintained by the threading implementation. 
 *The thread ID returned by gettid() is a number (similar to a process ID) that is assigned by the kernel.
 *Although each POSIX thread has a unique kernel thread ID in the Linux NPTL threading implementation,
 *an application generally doesn’t need to know about the kernel IDs (and won’t be portable if it depends on knowing them).
 */

